### ISSUE TITLE
types-aiobotocore has incorrect type for s3 Response Body

### ISSUE THREAD

**Issue by carlos-alberto** [youtype/mypy_boto3_builder#154]
**Describe the bug**
types-aiobotocore states that s3 `get_object` returns a response of type `GetObjectOutputTypeDef`, which has a `"Body"` value of type `botocore.response.StreamingBody`, the type should be `aiobotocore.response.StreamingBody`. The two `StreamingBody` classes have very different api's the most major of which is that `aitobotocore.response.StreamingBody` is `async`.

**To Reproduce**

1. Install `types-aiobotocore[s3]`
2. Check the type of `get_output` response:
     

```python
from types_aiobotocore_s3.type_defs import GetObjectOutputTypeDef
import botocore
from aiobotocore.session import get_session

session = get_session()

async with session.create_client("s3") as client:
    val = await client.get_object(Bucket="...", Key="...")
    print(GetObjectOutputTypeDef.__annotations__["Body"])
    print(type(val["Body"]))
    print(isinstance(val["Body"], botocore.response.StreamingBody))
```

**Actual output**

```
botocore.response.StreamingBody
<class 'aiobotocore.response.StreamingBody'>
False
...
```

**Expected output**

```
aiobotocore.response.StreamingBody
<class 'aiobotocore.response.StreamingBody'>
True
```

**Comment by vemel** [comment]
Makes sense, I completely overlooked it. Will be fixed today.

**Comment by vemel** [comment]
So, looks like the issue is quite big.

In order to fix it properly, I have to:
- Avoid using classes from `boto3`/`botocore` directly and use `ExternalImport` instead
- In `AioBotocorePostprocessor`, I have to replace `botocore` external imports with `aiobotocore`

List ofsubstitutions:
 
- `botocore.response.StreamingBody` -> `aiobotocore.response.StreamingBody`
- `botocore.eventstream.EventStream` -> `aiobotocore.eventstream.AioEventStream`
- `botocore.config.Config` -> `aiobotocore.config.AioConfig`
- `botocore.waiter.Waiter` -> `aiobotocore.waiter.AIOWaiter`
- `botocore.paginate.Paginator` -> `aiobotocore.paginate.AioPaginator`
- `botocore.client.BaseClient` -> `aiobotocore.client.AioBaseClient`

**Comment by vemel** [comment]
Fixed in new `types-aiobotocore 2.3.4.post1`. Please update and let me know if it works as it should for you.

**Comment by carlos-alberto** [comment]
Thanks @vemel , will test asap

**Comment by carlos-alberto** [comment]
@vemel I can confirm it's all working from my side, thank you for the super quick turnaround!
