### ISSUE TITLE
Client detection fails when region name is specified in client call

### ISSUE THREAD

**Issue by tedivm** [youtype/mypy_boto3_builder#157]
**Describe the bug**

The client detection fails when a region name is applied.

**To Reproduce**

1. Install `boto3-stubs[rds]`
2. Run `mypy`/`pyright` on the following code sample. It should work just fine.

```python
rds_client = boto3.client("rds")
```

3. Run `mypy`/`pyright` on the following code sample. It will fail with pages of "notes" about not being able to detect the client.

```python
import boto3
rds_client = boto3.client("rds", region_name="us-west-2")
```

**Additional context**

This can be replicated on Github Actions and OSX using python 3.10.

**Comment by vemel** [comment]
Thank you for the report. However, I could not reproduce the error on the following code:

```python
import boto3
from typing_extensions import reveal_type

rds_client = boto3.client("rds", region_name="us-west-2")
reveal_type(rds_client)
```

- install: `pip install 'boto3-stubs[rds]'`
- run mypy 0.961: `mypy test.py` - no errors, type is revealed correctly as `RDSClient`
- run pyright 1.1.261: `npx pyright test.py` - no errors, type is revealed correctly as `RDSClient`


Could you please share your `mypy`/`pyright` output?

**Comment by vemel** [comment]
I believe there is a typo in your example: `parameters` is a Dict, so instead of `parameters.region` you want `parameters["region"]`.

The issue is that `mypy` tries to find an overload for `Callable[[str, Any], ...]`, because `parameters.region` is `Any`. 

If you change to `parameters["region"]`, which is `str`, `mypy` successfully finds and overload for `Callable[[str, str], ...]`.

Let me know if it works for you.
