### ISSUE TITLE
Large unnamed inline Union types impacts developer ergonomics

### ISSUE THREAD

**Issue by perlow** [youtype/mypy_boto3_builder#196]
An example of this is `LastEvaluatedKey` of `ScanOutputTableTypeDef`. It has the inline-type

```
  Dict[
            str,
            Union[
                bytes,
                bytearray,
                str,
                int,
                Decimal,
                bool,
                Set[int],
                Set[Decimal],
                Set[str],
                Set[bytes],
                Set[bytearray],
                Sequence[Any],
                Mapping[str, Any],
                None,
            ],
        ]
```

This means that if code calling `table.scan` needs to return this to its caller, it needs to replicate that very large type definition. Ideally, this would be a named type like LastEvaluatedKeyTypeDef which could then be referenced in application code.

**Comment by vemel** [comment]
Hello!

Thanks for the feature request. Yes, I was thinking about it. As you see, for now, I only have Literals and TypedDicts. It is a good idea to also have named type annotations for large types.

There are several issues with this approach:
- Naming. There is no corresponding `Shape`, so it has to reuse the parent name, e.g. `ScanOutputTableLastEvaluatedKeyValueType`
- Where to store them. I think I can create file `extras` and store types there
- In the case of `dynamodb` this is relatively easy to do because this particular type is created by me. Should we also name large `Unions` extracted from `botocore. Shape`

I will think about it. Also, feel free to share your ideas.
