### ISSUE TITLE
type SendMessageBatchRequestEntryQueueTypeDef missing in mypy-boto3-sqs 1.34.101

### ISSUE THREAD

**Issue by luizmineo** [youtype/mypy_boto3_builder#283]
I recently upgraded my project from mypy-boto3-sqs 1.34.0 to 1.34.101, and noticed a type check error due to a missing type `SendMessageBatchRequestEntryQueueTypeDef`

After further investigation, it seems that 1.34.0 contains 2 identical TypeDict's: `SendMessageBatchRequestEntryTypeDef` and `SendMessageBatchRequestEntryQueueTypeDef`, and later versions contains only the first one. 

According to the AWS documentation, the [SendMessageBatchRequestEntry](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessageBatchRequestEntry.html) type is indeed the correct one, so I just want to confirm if this change was intentional, and it is safe to replace references to `SendMessageBatchRequestEntryQueueTypeDef` with `SendMessageBatchRequestEntryTypeDef`.

Thank you!

**Comment by vemel** [comment]
Hello! Thank you for the report.

Yes, the current behavior is correct, there should only be `SendMessageBatchRequestEntryTypeDef`. There used to be two of them because I had a logic to create a separate resource-specific TypeDef if it had different members or totality. Unfortunately, there was a bug that did not compare global and resource-specific TypeDefs correctly, so there was an unnecessary duplication.

**Comment by luizmineo** [comment]
Thanks for the response. Yes, it is working as expected.
